import Navbar from "@/components/Navbar";
import Main from "@/components/Main";
import Head from "next/head";
import React from "react";
import About from "@/components/About";
import Skills from "@/components/Skills";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";

const index = () => {
  return (
    <div>
      <Head>
        <title>Pranay || Fronted Developer</title>
        <meta name="description" content="Generated by the next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Main />
        <About />
        <Skills />
        <Projects />
        <Contact />
      </div>
    </div>
  );
};

export default index;
